version: 1

update_configs:
    - package_manager: 'javascript'
      directory: '/'
      update_schedule: 'live'
      allowed_updates:
          - match:
                dependency_type: 'development'
                update_type: 'all'
      automerged_updates:
          - match:
                dependency_type: 'development'
                update_type: 'all'
      target_branch: master
